### ISSUE TITLE
bpls Precedence over ADIOS1

### ISSUE THREAD

**Issue by ax3l** [conda-forge/adios2-feedstock#72]
`adios` and `adios2` both ship a `bpls` CLI tool:
```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::adios-1.13.1-nompi_h476e72a_1121, conda-forge/linux-64::libadios2-2.8.3-nompi_h008eccf_105
  path: 'bin/bpls'
```

Both packages can be used at the same time, e.g., are so in `openpmd-api` and in older versions of `adios2` itself. But, in case both packages are loaded at the same time, the `bpls` tool from `ADIOS2` should be used, because it is backwards compatible (while `bpls` from ADIOS1 can only read the its files).

https://github.com/conda-forge/staged-recipes/pull/22171#issuecomment-1577409324

cc @carterbox

**Comment by carterbox** [comment]
My suggestion is that you split the adios recipe like the adios2 recipe is split, so there would be four packages: adios, libadios, adios2, libadios2. Then make adios2 and adios mutually exclusive using `run_constrained`.

This would probably allow the following valid environments:

- adios, libadios, libadios2
- adios2, libadios, libadios2

But the following would not be allowed:

- adios, adios2, ...

Conda doesn't support the concept that two packages supply the same tool and that one should take precedence over the other. In order to accomplish something like that, bpls would need to be published from its own feedstock.

If the maintainers of adios2 wanted their tools to be co-installable with the old ones, they should/would have renamed thier tools to something like bpls2.

**Comment by carterbox** [comment]
That be a non-canonical break the API of the package for anyone still using adios1. You can't control when downstream users choose to stop using adios1.

**Comment by ax3l** [comment]
Since ADIOS1 is EOL, I think that is ok. Also, ADIOS2 `bpls` can read its data. I am really transitioning out here, years after the main devs stopped supporting it. From what I know from the developer community, depends also moved to ADIOS2 already.

**Comment by carterbox** [comment]
If adios1 is EOL, then don't use it in any of your packages and you won't have any collision problems?

**Comment by ax3l** [comment]
Only around for the C lib that reads legacy files, removed in future releases.

**Comment by minrk** [comment]
We can add a `run_constrained` to prevent them being in the same env, to make the conflict explicit. Would that be desirable?

**Comment by ax3l** [comment]
No, I really want them in the same env.

It's really no problem, I am probably the only left user of ADIOS1 and renaming that CLI to `bp3ls` fixes the long-standing issue that it took precedence over ADIOS2's, which can read both.
